export const routingAbout={
    namespaced:true,
    actions:{  
    },
    mutations:{
         FIRST_ROUTING(state,router){
            if(state.first_path==='info'){
                router.push({
                    name:'info',
                })
            }
            if(state.first_path==='cli'){
                router.push({
                    name:'cli',
                })
            }
         },
         SECOND_ROUTING(state,router){
            if(state.second_path==='create'){
                router.push({
                    name:'create',
                })
            }
            if(state.second_path==='update'){
                router.push({
                    name:'update',
                })
            }
            if(state.second_path==='delete'){
                router.push({
                    name:'delete',
                })
            }
         }
    },
    state:{
        first_path:'',
        second_path:''
    }

}